version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysqlContainer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
