version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysqlContainer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-initdb:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:latest
    container_name: postgresContainer
    restart: always
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
  postgres_data:
